//-----------------------------------------------------------------------------
// copyright 2025, jessa gillespie, all rights reserved.
//----------------------------------------------------------------------------- 

#include "Rot_Assignment_Quat.cpp"   
#include "Rot_Assignment_Rot.cpp"   
#include "Rot_Set_Rot.cpp"    
#include "Rot_Quat_Constructor.cpp"  

#include "Rot_X_Constructor.cpp"                                                          
#include "Rot_Y_Constructor.cpp"                                            
#include "Rot_Z_Constructor.cpp" 
#include "Rot_XYZ_Constructor.cpp" 
#include "Rot_XZY_Constructor.cpp" 
#include "Rot_YXZ_Constructor.cpp" 
#include "Rot_YZX_Constructor.cpp" 
#include "Rot_ZXY_Constructor.cpp" 
#include "Rot_ZYX_Constructor.cpp" 
#include "Rot_Set_AxisAngle.cpp"  
#include "Rot_Set_UnitAxisAngle.cpp" 
#include "Rot_Set_InverseOrient.cpp"                
#include "Rot_Set_Orient.cpp"                              
#include "Rot_X_Set.cpp"                                                                                                   
#include "Rot_Y_Set.cpp"                                                    
#include "Rot_Z_Set.cpp"  
#include "Rot_XYZ_Set.cpp"    
#include "Rot_XZY_Set.cpp"    
#include "Rot_YXZ_Set.cpp"   
#include "Rot_YZX_Set.cpp"  
#include "Rot_ZXY_Set.cpp" 
#include "Rot_ZYX_Set.cpp" 
#include "Rot_AxisAngle.cpp"      
#include "Rot_UnitAxisAngle.cpp" 
#include "Rot_InverseOrient.cpp"                                    
#include "Rot_Orient.cpp"  
#include "Rot_Mult_Quat.cpp"
#include "Rot_MultEqual_Quat.cpp" 
#include "Rot_RotAxisAngle.cpp"                                            
#include "Rot_RotInverseOrient.cpp"
#include "Rot_RotOrient.cpp"   
#include "Rot_SET_MatrixRotAxisAngle.cpp"
#include "Rot_SET_MatrixRotInverseOrient.cpp"
#include "Rot_SET_MatrixRotOrient.cpp"
#include "Rot_SET_RotXYZ.cpp"

// ---  End of File ---
