//-----------------------------------------------------------------------------
// copyright 2025, jessa gillespie, all rights reserved.
//----------------------------------------------------------------------------- 

#include "S_Set_Ident.cpp"
#include "S_Set_Inv_Affine.cpp"
#include "S_Set_Inv_General.cpp"
#include "S_Set_Inv_Rot.cpp"
#include "S_Set_Inv_RotScale.cpp"
#include "S_Set_Inv_RotTrans.cpp"
#include "S_Set_Inv_Scale.cpp"
#include "S_Set_Inv_Trans.cpp"
#include "S_Set_Inv_TransScale.cpp"

#include "S_Set_Mat4.cpp"
#include "S_Set_Row0.cpp"
#include "S_Set_Row1.cpp"
#include "S_Set_Row2.cpp"
#include "S_Set_Row3.cpp"
#include "S_Set_T.cpp"
#include "S_Set_T0.cpp"
#include "S_Set_Vec4.cpp"

#include "S0.cpp"     
#include "S1.cpp"                                                     
#include "S2.cpp"  
#include "S3.cpp"  
#include "S4.cpp"  
#include "S5.cpp"  
#include "S6.cpp"  
#include "S7.cpp"  
#include "S8.cpp"  
#include "S9.cpp"  
#include "S10.cpp"  
#include "S11.cpp"  
#include "S12.cpp"  
#include "S13.cpp"  
#include "S14.cpp"  
#include "S15.cpp"  

#include "SB0.cpp"     
#include "SB1.cpp"                                                     
#include "SB2.cpp"  
#include "SB3.cpp"  
#include "SB4.cpp"  
#include "SB5.cpp"  
#include "SB6.cpp"  
#include "SB7.cpp"  
#include "SB8.cpp"  
#include "SB9.cpp"  
#include "SB10.cpp"  
#include "SB11.cpp"  
#include "SB12.cpp"  
#include "SB13.cpp"  
#include "SB14.cpp"  
#include "SB15.cpp"  


// --- End of File ---
