//-----------------------------------------------------------------------------
// copyright 2025, jessa gillespie, all rights reserved.
//----------------------------------------------------------------------------- 

#include "T1.cpp"                                                     
#include "T2.cpp"  
#include "T3.cpp"  
#include "T4.cpp"  
#include "T5.cpp"  
#include "T6.cpp"  
#include "T7.cpp"  
#include "T8.cpp"  
#include "T9.cpp"  
#include "T10.cpp"  
#include "T11.cpp"  
#include "T12.cpp"  
#include "T13.cpp"  
#include "T14.cpp"  
#include "T15.cpp"  
#include "T16.cpp"  
#include "T17.cpp"  
#include "T18.cpp"  
#include "T19.cpp"  
#include "T20.cpp"  
#include "T21.cpp"  
#include "T22.cpp"  
#include "T23.cpp"  
#include "T24.cpp"  
#include "T25.cpp"  
#include "T26.cpp"  
#include "T27.cpp"  
#include "T28.cpp"  
#include "T29.cpp"  
#include "T30.cpp"  
#include "T31.cpp"  
#include "T32.cpp"  
#include "T33.cpp"  
#include "T34.cpp"  
#include "T35.cpp"  
#include "T36.cpp"  
#include "T37.cpp"


// --- End of File ---
