// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: BoneEntry.proto
// Protobuf C++ Version: 5.27.2

#ifndef GOOGLE_PROTOBUF_INCLUDED_BoneEntry_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_BoneEntry_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "Vec3Data.pb.h"
#include "QuatData.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_BoneEntry_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_BoneEntry_2eproto {
  static const ::uint32_t offsets[];
};
class BoneEntry_proto;
struct BoneEntry_protoDefaultTypeInternal;
extern BoneEntry_protoDefaultTypeInternal _BoneEntry_proto_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class BoneEntry_proto final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:BoneEntry_proto) */ {
 public:
  inline BoneEntry_proto() : BoneEntry_proto(nullptr) {}
  ~BoneEntry_proto() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BoneEntry_proto(
      ::google::protobuf::internal::ConstantInitialized);

  inline BoneEntry_proto(const BoneEntry_proto& from) : BoneEntry_proto(nullptr, from) {}
  inline BoneEntry_proto(BoneEntry_proto&& from) noexcept
      : BoneEntry_proto(nullptr, std::move(from)) {}
  inline BoneEntry_proto& operator=(const BoneEntry_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline BoneEntry_proto& operator=(BoneEntry_proto&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const BoneEntry_proto& default_instance() {
    return *internal_default_instance();
  }
  static inline const BoneEntry_proto* internal_default_instance() {
    return reinterpret_cast<const BoneEntry_proto*>(
        &_BoneEntry_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(BoneEntry_proto& a, BoneEntry_proto& b) { a.Swap(&b); }
  inline void Swap(BoneEntry_proto* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BoneEntry_proto* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BoneEntry_proto* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::MessageLite::DefaultConstruct<BoneEntry_proto>(arena);
  }
  void CheckTypeAndMergeFrom(
      const ::google::protobuf::MessageLite& from) final;
  void CopyFrom(const BoneEntry_proto& from);
  void MergeFrom(const BoneEntry_proto& from);
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(BoneEntry_proto* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "BoneEntry_proto"; }

 protected:
  explicit BoneEntry_proto(::google::protobuf::Arena* arena);
  BoneEntry_proto(::google::protobuf::Arena* arena, const BoneEntry_proto& from);
  BoneEntry_proto(::google::protobuf::Arena* arena, BoneEntry_proto&& from) noexcept
      : BoneEntry_proto(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData() const final;

 public:
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSFieldNumber = 1,
    kQFieldNumber = 2,
    kTFieldNumber = 3,
  };
  // optional .Vec3Data_proto S = 1;
  bool has_s() const;
  void clear_s() ;
  const ::Vec3Data_proto& s() const;
  PROTOBUF_NODISCARD ::Vec3Data_proto* release_s();
  ::Vec3Data_proto* mutable_s();
  void set_allocated_s(::Vec3Data_proto* value);
  void unsafe_arena_set_allocated_s(::Vec3Data_proto* value);
  ::Vec3Data_proto* unsafe_arena_release_s();

  private:
  const ::Vec3Data_proto& _internal_s() const;
  ::Vec3Data_proto* _internal_mutable_s();

  public:
  // optional .QuatData_proto Q = 2;
  bool has_q() const;
  void clear_q() ;
  const ::QuatData_proto& q() const;
  PROTOBUF_NODISCARD ::QuatData_proto* release_q();
  ::QuatData_proto* mutable_q();
  void set_allocated_q(::QuatData_proto* value);
  void unsafe_arena_set_allocated_q(::QuatData_proto* value);
  ::QuatData_proto* unsafe_arena_release_q();

  private:
  const ::QuatData_proto& _internal_q() const;
  ::QuatData_proto* _internal_mutable_q();

  public:
  // optional .Vec3Data_proto T = 3;
  bool has_t() const;
  void clear_t() ;
  const ::Vec3Data_proto& t() const;
  PROTOBUF_NODISCARD ::Vec3Data_proto* release_t();
  ::Vec3Data_proto* mutable_t();
  void set_allocated_t(::Vec3Data_proto* value);
  void unsafe_arena_set_allocated_t(::Vec3Data_proto* value);
  ::Vec3Data_proto* unsafe_arena_release_t();

  private:
  const ::Vec3Data_proto& _internal_t() const;
  ::Vec3Data_proto* _internal_mutable_t();

  public:
  // @@protoc_insertion_point(class_scope:BoneEntry_proto)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 3,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_BoneEntry_proto_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const BoneEntry_proto& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::Vec3Data_proto* s_;
    ::QuatData_proto* q_;
    ::Vec3Data_proto* t_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_BoneEntry_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// BoneEntry_proto

// optional .Vec3Data_proto S = 1;
inline bool BoneEntry_proto::has_s() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.s_ != nullptr);
  return value;
}
inline const ::Vec3Data_proto& BoneEntry_proto::_internal_s() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Vec3Data_proto* p = _impl_.s_;
  return p != nullptr ? *p : reinterpret_cast<const ::Vec3Data_proto&>(::_Vec3Data_proto_default_instance_);
}
inline const ::Vec3Data_proto& BoneEntry_proto::s() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:BoneEntry_proto.S)
  return _internal_s();
}
inline void BoneEntry_proto::unsafe_arena_set_allocated_s(::Vec3Data_proto* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.s_);
  }
  _impl_.s_ = reinterpret_cast<::Vec3Data_proto*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:BoneEntry_proto.S)
}
inline ::Vec3Data_proto* BoneEntry_proto::release_s() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Vec3Data_proto* released = _impl_.s_;
  _impl_.s_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::Vec3Data_proto* BoneEntry_proto::unsafe_arena_release_s() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:BoneEntry_proto.S)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Vec3Data_proto* temp = _impl_.s_;
  _impl_.s_ = nullptr;
  return temp;
}
inline ::Vec3Data_proto* BoneEntry_proto::_internal_mutable_s() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.s_ == nullptr) {
    auto* p = ::google::protobuf::MessageLite::DefaultConstruct<::Vec3Data_proto>(GetArena());
    _impl_.s_ = reinterpret_cast<::Vec3Data_proto*>(p);
  }
  return _impl_.s_;
}
inline ::Vec3Data_proto* BoneEntry_proto::mutable_s() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::Vec3Data_proto* _msg = _internal_mutable_s();
  // @@protoc_insertion_point(field_mutable:BoneEntry_proto.S)
  return _msg;
}
inline void BoneEntry_proto::set_allocated_s(::Vec3Data_proto* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.s_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.s_ = reinterpret_cast<::Vec3Data_proto*>(value);
  // @@protoc_insertion_point(field_set_allocated:BoneEntry_proto.S)
}

// optional .QuatData_proto Q = 2;
inline bool BoneEntry_proto::has_q() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.q_ != nullptr);
  return value;
}
inline const ::QuatData_proto& BoneEntry_proto::_internal_q() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::QuatData_proto* p = _impl_.q_;
  return p != nullptr ? *p : reinterpret_cast<const ::QuatData_proto&>(::_QuatData_proto_default_instance_);
}
inline const ::QuatData_proto& BoneEntry_proto::q() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:BoneEntry_proto.Q)
  return _internal_q();
}
inline void BoneEntry_proto::unsafe_arena_set_allocated_q(::QuatData_proto* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.q_);
  }
  _impl_.q_ = reinterpret_cast<::QuatData_proto*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:BoneEntry_proto.Q)
}
inline ::QuatData_proto* BoneEntry_proto::release_q() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::QuatData_proto* released = _impl_.q_;
  _impl_.q_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::QuatData_proto* BoneEntry_proto::unsafe_arena_release_q() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:BoneEntry_proto.Q)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::QuatData_proto* temp = _impl_.q_;
  _impl_.q_ = nullptr;
  return temp;
}
inline ::QuatData_proto* BoneEntry_proto::_internal_mutable_q() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.q_ == nullptr) {
    auto* p = ::google::protobuf::MessageLite::DefaultConstruct<::QuatData_proto>(GetArena());
    _impl_.q_ = reinterpret_cast<::QuatData_proto*>(p);
  }
  return _impl_.q_;
}
inline ::QuatData_proto* BoneEntry_proto::mutable_q() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::QuatData_proto* _msg = _internal_mutable_q();
  // @@protoc_insertion_point(field_mutable:BoneEntry_proto.Q)
  return _msg;
}
inline void BoneEntry_proto::set_allocated_q(::QuatData_proto* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.q_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.q_ = reinterpret_cast<::QuatData_proto*>(value);
  // @@protoc_insertion_point(field_set_allocated:BoneEntry_proto.Q)
}

// optional .Vec3Data_proto T = 3;
inline bool BoneEntry_proto::has_t() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.t_ != nullptr);
  return value;
}
inline const ::Vec3Data_proto& BoneEntry_proto::_internal_t() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Vec3Data_proto* p = _impl_.t_;
  return p != nullptr ? *p : reinterpret_cast<const ::Vec3Data_proto&>(::_Vec3Data_proto_default_instance_);
}
inline const ::Vec3Data_proto& BoneEntry_proto::t() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:BoneEntry_proto.T)
  return _internal_t();
}
inline void BoneEntry_proto::unsafe_arena_set_allocated_t(::Vec3Data_proto* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.t_);
  }
  _impl_.t_ = reinterpret_cast<::Vec3Data_proto*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:BoneEntry_proto.T)
}
inline ::Vec3Data_proto* BoneEntry_proto::release_t() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::Vec3Data_proto* released = _impl_.t_;
  _impl_.t_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::Vec3Data_proto* BoneEntry_proto::unsafe_arena_release_t() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:BoneEntry_proto.T)

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::Vec3Data_proto* temp = _impl_.t_;
  _impl_.t_ = nullptr;
  return temp;
}
inline ::Vec3Data_proto* BoneEntry_proto::_internal_mutable_t() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.t_ == nullptr) {
    auto* p = ::google::protobuf::MessageLite::DefaultConstruct<::Vec3Data_proto>(GetArena());
    _impl_.t_ = reinterpret_cast<::Vec3Data_proto*>(p);
  }
  return _impl_.t_;
}
inline ::Vec3Data_proto* BoneEntry_proto::mutable_t() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000004u;
  ::Vec3Data_proto* _msg = _internal_mutable_t();
  // @@protoc_insertion_point(field_mutable:BoneEntry_proto.T)
  return _msg;
}
inline void BoneEntry_proto::set_allocated_t(::Vec3Data_proto* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.t_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }

  _impl_.t_ = reinterpret_cast<::Vec3Data_proto*>(value);
  // @@protoc_insertion_point(field_set_allocated:BoneEntry_proto.T)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_BoneEntry_2eproto_2epb_2eh
