// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ClipData.proto
// Protobuf C++ Version: 5.27.2

#ifndef GOOGLE_PROTOBUF_INCLUDED_ClipData_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_ClipData_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "FrameBucketEntry.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ClipData_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ClipData_2eproto {
  static const ::uint32_t offsets[];
};
class ClipData_proto;
struct ClipData_protoDefaultTypeInternal;
extern ClipData_protoDefaultTypeInternal _ClipData_proto_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class ClipData_proto final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:ClipData_proto) */ {
 public:
  inline ClipData_proto() : ClipData_proto(nullptr) {}
  ~ClipData_proto() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ClipData_proto(
      ::google::protobuf::internal::ConstantInitialized);

  inline ClipData_proto(const ClipData_proto& from) : ClipData_proto(nullptr, from) {}
  inline ClipData_proto(ClipData_proto&& from) noexcept
      : ClipData_proto(nullptr, std::move(from)) {}
  inline ClipData_proto& operator=(const ClipData_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClipData_proto& operator=(ClipData_proto&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const ClipData_proto& default_instance() {
    return *internal_default_instance();
  }
  static inline const ClipData_proto* internal_default_instance() {
    return reinterpret_cast<const ClipData_proto*>(
        &_ClipData_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ClipData_proto& a, ClipData_proto& b) { a.Swap(&b); }
  inline void Swap(ClipData_proto* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ClipData_proto* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ClipData_proto* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::MessageLite::DefaultConstruct<ClipData_proto>(arena);
  }
  void CheckTypeAndMergeFrom(
      const ::google::protobuf::MessageLite& from) final;
  void CopyFrom(const ClipData_proto& from);
  void MergeFrom(const ClipData_proto& from);
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ClipData_proto* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "ClipData_proto"; }

 protected:
  explicit ClipData_proto(::google::protobuf::Arena* arena);
  ClipData_proto(::google::protobuf::Arena* arena, const ClipData_proto& from);
  ClipData_proto(::google::protobuf::Arena* arena, ClipData_proto&& from) noexcept
      : ClipData_proto(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData() const final;

 public:
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPoFrameBucketEntryFieldNumber = 4,
    kPVersionFieldNumber = 1,
    kNumKeyFramesFieldNumber = 2,
    kNumNodesFieldNumber = 3,
  };
  // repeated .FrameBucketEntry_proto poFrameBucketEntry = 4;
  int poframebucketentry_size() const;
  private:
  int _internal_poframebucketentry_size() const;

  public:
  void clear_poframebucketentry() ;
  ::FrameBucketEntry_proto* mutable_poframebucketentry(int index);
  ::google::protobuf::RepeatedPtrField<::FrameBucketEntry_proto>* mutable_poframebucketentry();

  private:
  const ::google::protobuf::RepeatedPtrField<::FrameBucketEntry_proto>& _internal_poframebucketentry() const;
  ::google::protobuf::RepeatedPtrField<::FrameBucketEntry_proto>* _internal_mutable_poframebucketentry();
  public:
  const ::FrameBucketEntry_proto& poframebucketentry(int index) const;
  ::FrameBucketEntry_proto* add_poframebucketentry();
  const ::google::protobuf::RepeatedPtrField<::FrameBucketEntry_proto>& poframebucketentry() const;
  // optional bytes pVersion = 1;
  bool has_pversion() const;
  void clear_pversion() ;
  const std::string& pversion() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_pversion(Arg_&& arg, Args_... args);
  std::string* mutable_pversion();
  PROTOBUF_NODISCARD std::string* release_pversion();
  void set_allocated_pversion(std::string* value);

  private:
  const std::string& _internal_pversion() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pversion(
      const std::string& value);
  std::string* _internal_mutable_pversion();

  public:
  // optional uint32 numKeyFrames = 2;
  bool has_numkeyframes() const;
  void clear_numkeyframes() ;
  ::uint32_t numkeyframes() const;
  void set_numkeyframes(::uint32_t value);

  private:
  ::uint32_t _internal_numkeyframes() const;
  void _internal_set_numkeyframes(::uint32_t value);

  public:
  // optional uint32 numNodes = 3;
  bool has_numnodes() const;
  void clear_numnodes() ;
  ::uint32_t numnodes() const;
  void set_numnodes(::uint32_t value);

  private:
  ::uint32_t _internal_numnodes() const;
  void _internal_set_numnodes(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:ClipData_proto)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 1,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_ClipData_proto_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ClipData_proto& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::FrameBucketEntry_proto > poframebucketentry_;
    ::google::protobuf::internal::ArenaStringPtr pversion_;
    ::uint32_t numkeyframes_;
    ::uint32_t numnodes_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ClipData_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ClipData_proto

// optional bytes pVersion = 1;
inline bool ClipData_proto::has_pversion() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void ClipData_proto::clear_pversion() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pversion_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ClipData_proto::pversion() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ClipData_proto.pVersion)
  return _internal_pversion();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ClipData_proto::set_pversion(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.pversion_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ClipData_proto.pVersion)
}
inline std::string* ClipData_proto::mutable_pversion() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_pversion();
  // @@protoc_insertion_point(field_mutable:ClipData_proto.pVersion)
  return _s;
}
inline const std::string& ClipData_proto::_internal_pversion() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pversion_.Get();
}
inline void ClipData_proto::_internal_set_pversion(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.pversion_.Set(value, GetArena());
}
inline std::string* ClipData_proto::_internal_mutable_pversion() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.pversion_.Mutable( GetArena());
}
inline std::string* ClipData_proto::release_pversion() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ClipData_proto.pVersion)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.pversion_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.pversion_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void ClipData_proto::set_allocated_pversion(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.pversion_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.pversion_.IsDefault()) {
          _impl_.pversion_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ClipData_proto.pVersion)
}

// optional uint32 numKeyFrames = 2;
inline bool ClipData_proto::has_numkeyframes() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void ClipData_proto::clear_numkeyframes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.numkeyframes_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::uint32_t ClipData_proto::numkeyframes() const {
  // @@protoc_insertion_point(field_get:ClipData_proto.numKeyFrames)
  return _internal_numkeyframes();
}
inline void ClipData_proto::set_numkeyframes(::uint32_t value) {
  _internal_set_numkeyframes(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:ClipData_proto.numKeyFrames)
}
inline ::uint32_t ClipData_proto::_internal_numkeyframes() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.numkeyframes_;
}
inline void ClipData_proto::_internal_set_numkeyframes(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.numkeyframes_ = value;
}

// optional uint32 numNodes = 3;
inline bool ClipData_proto::has_numnodes() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void ClipData_proto::clear_numnodes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.numnodes_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::uint32_t ClipData_proto::numnodes() const {
  // @@protoc_insertion_point(field_get:ClipData_proto.numNodes)
  return _internal_numnodes();
}
inline void ClipData_proto::set_numnodes(::uint32_t value) {
  _internal_set_numnodes(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:ClipData_proto.numNodes)
}
inline ::uint32_t ClipData_proto::_internal_numnodes() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.numnodes_;
}
inline void ClipData_proto::_internal_set_numnodes(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.numnodes_ = value;
}

// repeated .FrameBucketEntry_proto poFrameBucketEntry = 4;
inline int ClipData_proto::_internal_poframebucketentry_size() const {
  return _internal_poframebucketentry().size();
}
inline int ClipData_proto::poframebucketentry_size() const {
  return _internal_poframebucketentry_size();
}
inline ::FrameBucketEntry_proto* ClipData_proto::mutable_poframebucketentry(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:ClipData_proto.poFrameBucketEntry)
  return _internal_mutable_poframebucketentry()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::FrameBucketEntry_proto>* ClipData_proto::mutable_poframebucketentry()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:ClipData_proto.poFrameBucketEntry)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_poframebucketentry();
}
inline const ::FrameBucketEntry_proto& ClipData_proto::poframebucketentry(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ClipData_proto.poFrameBucketEntry)
  return _internal_poframebucketentry().Get(index);
}
inline ::FrameBucketEntry_proto* ClipData_proto::add_poframebucketentry() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::FrameBucketEntry_proto* _add = _internal_mutable_poframebucketentry()->Add();
  // @@protoc_insertion_point(field_add:ClipData_proto.poFrameBucketEntry)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::FrameBucketEntry_proto>& ClipData_proto::poframebucketentry() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:ClipData_proto.poFrameBucketEntry)
  return _internal_poframebucketentry();
}
inline const ::google::protobuf::RepeatedPtrField<::FrameBucketEntry_proto>&
ClipData_proto::_internal_poframebucketentry() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.poframebucketentry_;
}
inline ::google::protobuf::RepeatedPtrField<::FrameBucketEntry_proto>*
ClipData_proto::_internal_mutable_poframebucketentry() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.poframebucketentry_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_ClipData_2eproto_2epb_2eh
