// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: FrameBucketEntry.proto
// Protobuf C++ Version: 5.27.2

#include "FrameBucketEntry.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr FrameBucketEntry_proto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        poboneentry_{},
        keyframe_{0u},
        numnodes_{0u},
        keytime_{0},
        keytimeindex_{0} {}

template <typename>
PROTOBUF_CONSTEXPR FrameBucketEntry_proto::FrameBucketEntry_proto(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct FrameBucketEntry_protoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FrameBucketEntry_protoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FrameBucketEntry_protoDefaultTypeInternal() {}
  union {
    FrameBucketEntry_proto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FrameBucketEntry_protoDefaultTypeInternal _FrameBucketEntry_proto_default_instance_;
// ===================================================================

class FrameBucketEntry_proto::_Internal {
 public:
  using HasBits =
      decltype(std::declval<FrameBucketEntry_proto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(FrameBucketEntry_proto, _impl_._has_bits_);
};

void FrameBucketEntry_proto::clear_poboneentry() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.poboneentry_.Clear();
}
FrameBucketEntry_proto::FrameBucketEntry_proto(::google::protobuf::Arena* arena)
    : ::google::protobuf::MessageLite(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:FrameBucketEntry_proto)
}
inline PROTOBUF_NDEBUG_INLINE FrameBucketEntry_proto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::FrameBucketEntry_proto& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        poboneentry_{visibility, arena, from.poboneentry_} {}

FrameBucketEntry_proto::FrameBucketEntry_proto(
    ::google::protobuf::Arena* arena,
    const FrameBucketEntry_proto& from)
    : ::google::protobuf::MessageLite(arena) {
  FrameBucketEntry_proto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, keyframe_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, keyframe_),
           offsetof(Impl_, keytimeindex_) -
               offsetof(Impl_, keyframe_) +
               sizeof(Impl_::keytimeindex_));

  // @@protoc_insertion_point(copy_constructor:FrameBucketEntry_proto)
}
inline PROTOBUF_NDEBUG_INLINE FrameBucketEntry_proto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        poboneentry_{visibility, arena} {}

inline void FrameBucketEntry_proto::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, keyframe_),
           0,
           offsetof(Impl_, keytimeindex_) -
               offsetof(Impl_, keyframe_) +
               sizeof(Impl_::keytimeindex_));
}
FrameBucketEntry_proto::~FrameBucketEntry_proto() {
  // @@protoc_insertion_point(destructor:FrameBucketEntry_proto)
  _internal_metadata_.Delete<std::string>();
  SharedDtor();
}
inline void FrameBucketEntry_proto::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
FrameBucketEntry_proto::GetClassData() const {
  PROTOBUF_CONSTINIT static const ClassDataLite<23> _data_ =
      {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(FrameBucketEntry_proto, _impl_._cached_size_),
              true,
          },
          "FrameBucketEntry_proto",
      };

  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 1, 0, 2> FrameBucketEntry_proto::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(FrameBucketEntry_proto, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_FrameBucketEntry_proto_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::FrameBucketEntry_proto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional uint32 keyFrame = 1;
    {::_pbi::TcParser::FastV32S1,
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(FrameBucketEntry_proto, _impl_.keyframe_)}},
    // optional uint32 numNodes = 2;
    {::_pbi::TcParser::FastV32S1,
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(FrameBucketEntry_proto, _impl_.numnodes_)}},
    // optional float keyTime = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 2, 0, PROTOBUF_FIELD_OFFSET(FrameBucketEntry_proto, _impl_.keytime_)}},
    // optional int32 keyTimeIndex = 4;
    {::_pbi::TcParser::FastV32S1,
     {32, 3, 0, PROTOBUF_FIELD_OFFSET(FrameBucketEntry_proto, _impl_.keytimeindex_)}},
    // repeated .BoneEntry_proto poBoneEntry = 5;
    {::_pbi::TcParser::FastMtR1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(FrameBucketEntry_proto, _impl_.poboneentry_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional uint32 keyFrame = 1;
    {PROTOBUF_FIELD_OFFSET(FrameBucketEntry_proto, _impl_.keyframe_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 numNodes = 2;
    {PROTOBUF_FIELD_OFFSET(FrameBucketEntry_proto, _impl_.numnodes_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional float keyTime = 3;
    {PROTOBUF_FIELD_OFFSET(FrameBucketEntry_proto, _impl_.keytime_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional int32 keyTimeIndex = 4;
    {PROTOBUF_FIELD_OFFSET(FrameBucketEntry_proto, _impl_.keytimeindex_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // repeated .BoneEntry_proto poBoneEntry = 5;
    {PROTOBUF_FIELD_OFFSET(FrameBucketEntry_proto, _impl_.poboneentry_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::BoneEntry_proto>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void FrameBucketEntry_proto::Clear() {
// @@protoc_insertion_point(message_clear_start:FrameBucketEntry_proto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.poboneentry_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    ::memset(&_impl_.keyframe_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.keytimeindex_) -
        reinterpret_cast<char*>(&_impl_.keyframe_)) + sizeof(_impl_.keytimeindex_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<std::string>();
}

::uint8_t* FrameBucketEntry_proto::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:FrameBucketEntry_proto)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional uint32 keyFrame = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this->_internal_keyframe(), target);
  }

  // optional uint32 numNodes = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this->_internal_numnodes(), target);
  }

  // optional float keyTime = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        3, this->_internal_keytime(), target);
  }

  // optional int32 keyTimeIndex = 4;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<4>(
            stream, this->_internal_keytimeindex(), target);
  }

  // repeated .BoneEntry_proto poBoneEntry = 5;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this->_internal_poboneentry_size());
       i < n; i++) {
    const auto& repfield = this->_internal_poboneentry().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            5, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:FrameBucketEntry_proto)
  return target;
}

::size_t FrameBucketEntry_proto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:FrameBucketEntry_proto)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // repeated .BoneEntry_proto poBoneEntry = 5;
  total_size += 1UL * this->_internal_poboneentry_size();
  for (const auto& msg : this->_internal_poboneentry()) {
    total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    // optional uint32 keyFrame = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this->_internal_keyframe());
    }

    // optional uint32 numNodes = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this->_internal_numnodes());
    }

    // optional float keyTime = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += 5;
    }

    // optional int32 keyTimeIndex = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this->_internal_keytimeindex());
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  _impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void FrameBucketEntry_proto::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const FrameBucketEntry_proto*>(
      &from));
}

void FrameBucketEntry_proto::MergeFrom(const FrameBucketEntry_proto& from) {
  FrameBucketEntry_proto* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:FrameBucketEntry_proto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_poboneentry()->MergeFrom(
      from._internal_poboneentry());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.keyframe_ = from._impl_.keyframe_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.numnodes_ = from._impl_.numnodes_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.keytime_ = from._impl_.keytime_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.keytimeindex_ = from._impl_.keytimeindex_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void FrameBucketEntry_proto::CopyFrom(const FrameBucketEntry_proto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:FrameBucketEntry_proto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void FrameBucketEntry_proto::InternalSwap(FrameBucketEntry_proto* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.poboneentry_.InternalSwap(&other->_impl_.poboneentry_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FrameBucketEntry_proto, _impl_.keytimeindex_)
      + sizeof(FrameBucketEntry_proto::_impl_.keytimeindex_)
      - PROTOBUF_FIELD_OFFSET(FrameBucketEntry_proto, _impl_.keyframe_)>(
          reinterpret_cast<char*>(&_impl_.keyframe_),
          reinterpret_cast<char*>(&other->_impl_.keyframe_));
}

// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
