// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: HierarchyData.proto
// Protobuf C++ Version: 5.27.2

#include "HierarchyData.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr HierarchyData_proto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        podata_{},
        _podata_cached_byte_size_{0},
        pversion_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        numjoints_{0u},
        maxdepth_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR HierarchyData_proto::HierarchyData_proto(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct HierarchyData_protoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HierarchyData_protoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HierarchyData_protoDefaultTypeInternal() {}
  union {
    HierarchyData_proto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HierarchyData_protoDefaultTypeInternal _HierarchyData_proto_default_instance_;
// ===================================================================

class HierarchyData_proto::_Internal {
 public:
  using HasBits =
      decltype(std::declval<HierarchyData_proto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(HierarchyData_proto, _impl_._has_bits_);
};

HierarchyData_proto::HierarchyData_proto(::google::protobuf::Arena* arena)
    : ::google::protobuf::MessageLite(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:HierarchyData_proto)
}
inline PROTOBUF_NDEBUG_INLINE HierarchyData_proto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::HierarchyData_proto& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        podata_{visibility, arena, from.podata_},
        _podata_cached_byte_size_{0},
        pversion_(arena, from.pversion_) {}

HierarchyData_proto::HierarchyData_proto(
    ::google::protobuf::Arena* arena,
    const HierarchyData_proto& from)
    : ::google::protobuf::MessageLite(arena) {
  HierarchyData_proto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, numjoints_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, numjoints_),
           offsetof(Impl_, maxdepth_) -
               offsetof(Impl_, numjoints_) +
               sizeof(Impl_::maxdepth_));

  // @@protoc_insertion_point(copy_constructor:HierarchyData_proto)
}
inline PROTOBUF_NDEBUG_INLINE HierarchyData_proto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        podata_{visibility, arena},
        _podata_cached_byte_size_{0},
        pversion_(arena) {}

inline void HierarchyData_proto::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, numjoints_),
           0,
           offsetof(Impl_, maxdepth_) -
               offsetof(Impl_, numjoints_) +
               sizeof(Impl_::maxdepth_));
}
HierarchyData_proto::~HierarchyData_proto() {
  // @@protoc_insertion_point(destructor:HierarchyData_proto)
  _internal_metadata_.Delete<std::string>();
  SharedDtor();
}
inline void HierarchyData_proto::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.pversion_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
HierarchyData_proto::GetClassData() const {
  PROTOBUF_CONSTINIT static const ClassDataLite<20> _data_ =
      {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(HierarchyData_proto, _impl_._cached_size_),
              true,
          },
          "HierarchyData_proto",
      };

  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 0, 2> HierarchyData_proto::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(HierarchyData_proto, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_HierarchyData_proto_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::HierarchyData_proto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated uint32 poData = 4;
    {::_pbi::TcParser::FastV32P1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(HierarchyData_proto, _impl_.podata_)}},
    // optional bytes pVersion = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(HierarchyData_proto, _impl_.pversion_)}},
    // optional uint32 numJoints = 2;
    {::_pbi::TcParser::FastV32S1,
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(HierarchyData_proto, _impl_.numjoints_)}},
    // optional uint32 maxDepth = 3;
    {::_pbi::TcParser::FastV32S1,
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(HierarchyData_proto, _impl_.maxdepth_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional bytes pVersion = 1;
    {PROTOBUF_FIELD_OFFSET(HierarchyData_proto, _impl_.pversion_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional uint32 numJoints = 2;
    {PROTOBUF_FIELD_OFFSET(HierarchyData_proto, _impl_.numjoints_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 maxDepth = 3;
    {PROTOBUF_FIELD_OFFSET(HierarchyData_proto, _impl_.maxdepth_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // repeated uint32 poData = 4;
    {PROTOBUF_FIELD_OFFSET(HierarchyData_proto, _impl_.podata_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedUInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void HierarchyData_proto::Clear() {
// @@protoc_insertion_point(message_clear_start:HierarchyData_proto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.podata_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.pversion_.ClearNonDefaultToEmpty();
  }
  if (cached_has_bits & 0x00000006u) {
    ::memset(&_impl_.numjoints_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.maxdepth_) -
        reinterpret_cast<char*>(&_impl_.numjoints_)) + sizeof(_impl_.maxdepth_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<std::string>();
}

::uint8_t* HierarchyData_proto::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:HierarchyData_proto)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional bytes pVersion = 1;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_pversion();
    target = stream->WriteBytesMaybeAliased(1, _s, target);
  }

  // optional uint32 numJoints = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this->_internal_numjoints(), target);
  }

  // optional uint32 maxDepth = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        3, this->_internal_maxdepth(), target);
  }

  // repeated uint32 poData = 4;
  {
    int byte_size = _impl_._podata_cached_byte_size_.Get();
    if (byte_size > 0) {
      target = stream->WriteUInt32Packed(
          4, _internal_podata(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:HierarchyData_proto)
  return target;
}

::size_t HierarchyData_proto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:HierarchyData_proto)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // repeated uint32 poData = 4;
  {
    std::size_t data_size = ::_pbi::WireFormatLite::UInt32Size(
        this->_internal_podata())
    ;
    _impl_._podata_cached_byte_size_.Set(::_pbi::ToCachedSize(data_size));
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // optional bytes pVersion = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this->_internal_pversion());
    }

    // optional uint32 numJoints = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this->_internal_numjoints());
    }

    // optional uint32 maxDepth = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this->_internal_maxdepth());
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  _impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void HierarchyData_proto::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const HierarchyData_proto*>(
      &from));
}

void HierarchyData_proto::MergeFrom(const HierarchyData_proto& from) {
  HierarchyData_proto* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:HierarchyData_proto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_podata()->MergeFrom(from._internal_podata());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_pversion(from._internal_pversion());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.numjoints_ = from._impl_.numjoints_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.maxdepth_ = from._impl_.maxdepth_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void HierarchyData_proto::CopyFrom(const HierarchyData_proto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:HierarchyData_proto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void HierarchyData_proto::InternalSwap(HierarchyData_proto* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.podata_.InternalSwap(&other->_impl_.podata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pversion_, &other->_impl_.pversion_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(HierarchyData_proto, _impl_.maxdepth_)
      + sizeof(HierarchyData_proto::_impl_.maxdepth_)
      - PROTOBUF_FIELD_OFFSET(HierarchyData_proto, _impl_.numjoints_)>(
          reinterpret_cast<char*>(&_impl_.numjoints_),
          reinterpret_cast<char*>(&other->_impl_.numjoints_));
}

// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
