// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: JointData.proto
// Protobuf C++ Version: 5.27.2

#include "JointData.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr JointData_proto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        pojointentry_{},
        _pojointentry_cached_byte_size_{0},
        numjoints_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR JointData_proto::JointData_proto(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct JointData_protoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR JointData_protoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~JointData_protoDefaultTypeInternal() {}
  union {
    JointData_proto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 JointData_protoDefaultTypeInternal _JointData_proto_default_instance_;
// ===================================================================

class JointData_proto::_Internal {
 public:
  using HasBits =
      decltype(std::declval<JointData_proto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(JointData_proto, _impl_._has_bits_);
};

JointData_proto::JointData_proto(::google::protobuf::Arena* arena)
    : ::google::protobuf::MessageLite(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:JointData_proto)
}
inline PROTOBUF_NDEBUG_INLINE JointData_proto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::JointData_proto& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        pojointentry_{visibility, arena, from.pojointentry_},
        _pojointentry_cached_byte_size_{0} {}

JointData_proto::JointData_proto(
    ::google::protobuf::Arena* arena,
    const JointData_proto& from)
    : ::google::protobuf::MessageLite(arena) {
  JointData_proto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.numjoints_ = from._impl_.numjoints_;

  // @@protoc_insertion_point(copy_constructor:JointData_proto)
}
inline PROTOBUF_NDEBUG_INLINE JointData_proto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        pojointentry_{visibility, arena},
        _pojointentry_cached_byte_size_{0} {}

inline void JointData_proto::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.numjoints_ = {};
}
JointData_proto::~JointData_proto() {
  // @@protoc_insertion_point(destructor:JointData_proto)
  _internal_metadata_.Delete<std::string>();
  SharedDtor();
}
inline void JointData_proto::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
JointData_proto::GetClassData() const {
  PROTOBUF_CONSTINIT static const ClassDataLite<16> _data_ =
      {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(JointData_proto, _impl_._cached_size_),
              true,
          },
          "JointData_proto",
      };

  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> JointData_proto::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(JointData_proto, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_JointData_proto_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::JointData_proto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated uint32 poJointEntry = 2;
    {::_pbi::TcParser::FastV32P1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(JointData_proto, _impl_.pojointentry_)}},
    // optional uint32 numJoints = 1;
    {::_pbi::TcParser::FastV32S1,
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(JointData_proto, _impl_.numjoints_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional uint32 numJoints = 1;
    {PROTOBUF_FIELD_OFFSET(JointData_proto, _impl_.numjoints_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // repeated uint32 poJointEntry = 2;
    {PROTOBUF_FIELD_OFFSET(JointData_proto, _impl_.pojointentry_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedUInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void JointData_proto::Clear() {
// @@protoc_insertion_point(message_clear_start:JointData_proto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.pojointentry_.Clear();
  _impl_.numjoints_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<std::string>();
}

::uint8_t* JointData_proto::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:JointData_proto)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional uint32 numJoints = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this->_internal_numjoints(), target);
  }

  // repeated uint32 poJointEntry = 2;
  {
    int byte_size = _impl_._pojointentry_cached_byte_size_.Get();
    if (byte_size > 0) {
      target = stream->WriteUInt32Packed(
          2, _internal_pojointentry(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:JointData_proto)
  return target;
}

::size_t JointData_proto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:JointData_proto)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // repeated uint32 poJointEntry = 2;
  {
    std::size_t data_size = ::_pbi::WireFormatLite::UInt32Size(
        this->_internal_pojointentry())
    ;
    _impl_._pojointentry_cached_byte_size_.Set(::_pbi::ToCachedSize(data_size));
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // optional uint32 numJoints = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_numjoints());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  _impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void JointData_proto::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const JointData_proto*>(
      &from));
}

void JointData_proto::MergeFrom(const JointData_proto& from) {
  JointData_proto* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:JointData_proto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_pojointentry()->MergeFrom(from._internal_pojointentry());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _this->_impl_.numjoints_ = from._impl_.numjoints_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void JointData_proto::CopyFrom(const JointData_proto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:JointData_proto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void JointData_proto::InternalSwap(JointData_proto* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.pojointentry_.InternalSwap(&other->_impl_.pojointentry_);
        swap(_impl_.numjoints_, other->_impl_.numjoints_);
}

// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
