// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: JointData.proto
// Protobuf C++ Version: 5.27.2

#ifndef GOOGLE_PROTOBUF_INCLUDED_JointData_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_JointData_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_JointData_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_JointData_2eproto {
  static const ::uint32_t offsets[];
};
class JointData_proto;
struct JointData_protoDefaultTypeInternal;
extern JointData_protoDefaultTypeInternal _JointData_proto_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class JointData_proto final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:JointData_proto) */ {
 public:
  inline JointData_proto() : JointData_proto(nullptr) {}
  ~JointData_proto() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR JointData_proto(
      ::google::protobuf::internal::ConstantInitialized);

  inline JointData_proto(const JointData_proto& from) : JointData_proto(nullptr, from) {}
  inline JointData_proto(JointData_proto&& from) noexcept
      : JointData_proto(nullptr, std::move(from)) {}
  inline JointData_proto& operator=(const JointData_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline JointData_proto& operator=(JointData_proto&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const JointData_proto& default_instance() {
    return *internal_default_instance();
  }
  static inline const JointData_proto* internal_default_instance() {
    return reinterpret_cast<const JointData_proto*>(
        &_JointData_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(JointData_proto& a, JointData_proto& b) { a.Swap(&b); }
  inline void Swap(JointData_proto* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(JointData_proto* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  JointData_proto* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::MessageLite::DefaultConstruct<JointData_proto>(arena);
  }
  void CheckTypeAndMergeFrom(
      const ::google::protobuf::MessageLite& from) final;
  void CopyFrom(const JointData_proto& from);
  void MergeFrom(const JointData_proto& from);
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(JointData_proto* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "JointData_proto"; }

 protected:
  explicit JointData_proto(::google::protobuf::Arena* arena);
  JointData_proto(::google::protobuf::Arena* arena, const JointData_proto& from);
  JointData_proto(::google::protobuf::Arena* arena, JointData_proto&& from) noexcept
      : JointData_proto(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData() const final;

 public:
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPoJointEntryFieldNumber = 2,
    kNumJointsFieldNumber = 1,
  };
  // repeated uint32 poJointEntry = 2;
  int pojointentry_size() const;
  private:
  int _internal_pojointentry_size() const;

  public:
  void clear_pojointentry() ;
  ::uint32_t pojointentry(int index) const;
  void set_pojointentry(int index, ::uint32_t value);
  void add_pojointentry(::uint32_t value);
  const ::google::protobuf::RepeatedField<::uint32_t>& pojointentry() const;
  ::google::protobuf::RepeatedField<::uint32_t>* mutable_pojointentry();

  private:
  const ::google::protobuf::RepeatedField<::uint32_t>& _internal_pojointentry() const;
  ::google::protobuf::RepeatedField<::uint32_t>* _internal_mutable_pojointentry();

  public:
  // optional uint32 numJoints = 1;
  bool has_numjoints() const;
  void clear_numjoints() ;
  ::uint32_t numjoints() const;
  void set_numjoints(::uint32_t value);

  private:
  ::uint32_t _internal_numjoints() const;
  void _internal_set_numjoints(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:JointData_proto)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_JointData_proto_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const JointData_proto& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<::uint32_t> pojointentry_;
    mutable ::google::protobuf::internal::CachedSize _pojointentry_cached_byte_size_;
    ::uint32_t numjoints_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_JointData_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// JointData_proto

// optional uint32 numJoints = 1;
inline bool JointData_proto::has_numjoints() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void JointData_proto::clear_numjoints() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.numjoints_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::uint32_t JointData_proto::numjoints() const {
  // @@protoc_insertion_point(field_get:JointData_proto.numJoints)
  return _internal_numjoints();
}
inline void JointData_proto::set_numjoints(::uint32_t value) {
  _internal_set_numjoints(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:JointData_proto.numJoints)
}
inline ::uint32_t JointData_proto::_internal_numjoints() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.numjoints_;
}
inline void JointData_proto::_internal_set_numjoints(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.numjoints_ = value;
}

// repeated uint32 poJointEntry = 2;
inline int JointData_proto::_internal_pojointentry_size() const {
  return _internal_pojointentry().size();
}
inline int JointData_proto::pojointentry_size() const {
  return _internal_pojointentry_size();
}
inline void JointData_proto::clear_pojointentry() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pojointentry_.Clear();
}
inline ::uint32_t JointData_proto::pojointentry(int index) const {
  // @@protoc_insertion_point(field_get:JointData_proto.poJointEntry)
  return _internal_pojointentry().Get(index);
}
inline void JointData_proto::set_pojointentry(int index, ::uint32_t value) {
  _internal_mutable_pojointentry()->Set(index, value);
  // @@protoc_insertion_point(field_set:JointData_proto.poJointEntry)
}
inline void JointData_proto::add_pojointentry(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_pojointentry()->Add(value);
  // @@protoc_insertion_point(field_add:JointData_proto.poJointEntry)
}
inline const ::google::protobuf::RepeatedField<::uint32_t>& JointData_proto::pojointentry() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:JointData_proto.poJointEntry)
  return _internal_pojointentry();
}
inline ::google::protobuf::RepeatedField<::uint32_t>* JointData_proto::mutable_pojointentry()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:JointData_proto.poJointEntry)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_pojointentry();
}
inline const ::google::protobuf::RepeatedField<::uint32_t>&
JointData_proto::_internal_pojointentry() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pojointentry_;
}
inline ::google::protobuf::RepeatedField<::uint32_t>* JointData_proto::_internal_mutable_pojointentry() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.pojointentry_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_JointData_2eproto_2epb_2eh
