// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: QuatData.proto
// Protobuf C++ Version: 5.27.2

#ifndef GOOGLE_PROTOBUF_INCLUDED_QuatData_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_QuatData_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_QuatData_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_QuatData_2eproto {
  static const ::uint32_t offsets[];
};
class QuatData_proto;
struct QuatData_protoDefaultTypeInternal;
extern QuatData_protoDefaultTypeInternal _QuatData_proto_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class QuatData_proto final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:QuatData_proto) */ {
 public:
  inline QuatData_proto() : QuatData_proto(nullptr) {}
  ~QuatData_proto() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR QuatData_proto(
      ::google::protobuf::internal::ConstantInitialized);

  inline QuatData_proto(const QuatData_proto& from) : QuatData_proto(nullptr, from) {}
  inline QuatData_proto(QuatData_proto&& from) noexcept
      : QuatData_proto(nullptr, std::move(from)) {}
  inline QuatData_proto& operator=(const QuatData_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline QuatData_proto& operator=(QuatData_proto&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const QuatData_proto& default_instance() {
    return *internal_default_instance();
  }
  static inline const QuatData_proto* internal_default_instance() {
    return reinterpret_cast<const QuatData_proto*>(
        &_QuatData_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(QuatData_proto& a, QuatData_proto& b) { a.Swap(&b); }
  inline void Swap(QuatData_proto* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(QuatData_proto* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  QuatData_proto* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::MessageLite::DefaultConstruct<QuatData_proto>(arena);
  }
  void CheckTypeAndMergeFrom(
      const ::google::protobuf::MessageLite& from) final;
  void CopyFrom(const QuatData_proto& from);
  void MergeFrom(const QuatData_proto& from);
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(QuatData_proto* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "QuatData_proto"; }

 protected:
  explicit QuatData_proto(::google::protobuf::Arena* arena);
  QuatData_proto(::google::protobuf::Arena* arena, const QuatData_proto& from);
  QuatData_proto(::google::protobuf::Arena* arena, QuatData_proto&& from) noexcept
      : QuatData_proto(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData() const final;

 public:
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kQxFieldNumber = 1,
    kQyFieldNumber = 2,
    kQzFieldNumber = 3,
    kQwFieldNumber = 4,
  };
  // optional float qx = 1;
  bool has_qx() const;
  void clear_qx() ;
  float qx() const;
  void set_qx(float value);

  private:
  float _internal_qx() const;
  void _internal_set_qx(float value);

  public:
  // optional float qy = 2;
  bool has_qy() const;
  void clear_qy() ;
  float qy() const;
  void set_qy(float value);

  private:
  float _internal_qy() const;
  void _internal_set_qy(float value);

  public:
  // optional float qz = 3;
  bool has_qz() const;
  void clear_qz() ;
  float qz() const;
  void set_qz(float value);

  private:
  float _internal_qz() const;
  void _internal_set_qz(float value);

  public:
  // optional float qw = 4;
  bool has_qw() const;
  void clear_qw() ;
  float qw() const;
  void set_qw(float value);

  private:
  float _internal_qw() const;
  void _internal_set_qw(float value);

  public:
  // @@protoc_insertion_point(class_scope:QuatData_proto)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_QuatData_proto_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const QuatData_proto& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    float qx_;
    float qy_;
    float qz_;
    float qw_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_QuatData_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// QuatData_proto

// optional float qx = 1;
inline bool QuatData_proto::has_qx() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void QuatData_proto::clear_qx() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.qx_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline float QuatData_proto::qx() const {
  // @@protoc_insertion_point(field_get:QuatData_proto.qx)
  return _internal_qx();
}
inline void QuatData_proto::set_qx(float value) {
  _internal_set_qx(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:QuatData_proto.qx)
}
inline float QuatData_proto::_internal_qx() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.qx_;
}
inline void QuatData_proto::_internal_set_qx(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.qx_ = value;
}

// optional float qy = 2;
inline bool QuatData_proto::has_qy() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void QuatData_proto::clear_qy() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.qy_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline float QuatData_proto::qy() const {
  // @@protoc_insertion_point(field_get:QuatData_proto.qy)
  return _internal_qy();
}
inline void QuatData_proto::set_qy(float value) {
  _internal_set_qy(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:QuatData_proto.qy)
}
inline float QuatData_proto::_internal_qy() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.qy_;
}
inline void QuatData_proto::_internal_set_qy(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.qy_ = value;
}

// optional float qz = 3;
inline bool QuatData_proto::has_qz() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void QuatData_proto::clear_qz() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.qz_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline float QuatData_proto::qz() const {
  // @@protoc_insertion_point(field_get:QuatData_proto.qz)
  return _internal_qz();
}
inline void QuatData_proto::set_qz(float value) {
  _internal_set_qz(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:QuatData_proto.qz)
}
inline float QuatData_proto::_internal_qz() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.qz_;
}
inline void QuatData_proto::_internal_set_qz(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.qz_ = value;
}

// optional float qw = 4;
inline bool QuatData_proto::has_qw() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void QuatData_proto::clear_qw() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.qw_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline float QuatData_proto::qw() const {
  // @@protoc_insertion_point(field_get:QuatData_proto.qw)
  return _internal_qw();
}
inline void QuatData_proto::set_qw(float value) {
  _internal_set_qw(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:QuatData_proto.qw)
}
inline float QuatData_proto::_internal_qw() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.qw_;
}
inline void QuatData_proto::_internal_set_qw(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.qw_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_QuatData_2eproto_2epb_2eh
