// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: QuatData.proto
// Protobuf C++ Version: 5.27.2

#include "QuatData.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr QuatData_proto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        qx_{0},
        qy_{0},
        qz_{0},
        qw_{0} {}

template <typename>
PROTOBUF_CONSTEXPR QuatData_proto::QuatData_proto(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct QuatData_protoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR QuatData_protoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~QuatData_protoDefaultTypeInternal() {}
  union {
    QuatData_proto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 QuatData_protoDefaultTypeInternal _QuatData_proto_default_instance_;
// ===================================================================

class QuatData_proto::_Internal {
 public:
  using HasBits =
      decltype(std::declval<QuatData_proto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(QuatData_proto, _impl_._has_bits_);
};

QuatData_proto::QuatData_proto(::google::protobuf::Arena* arena)
    : ::google::protobuf::MessageLite(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:QuatData_proto)
}
QuatData_proto::QuatData_proto(
    ::google::protobuf::Arena* arena, const QuatData_proto& from)
    : QuatData_proto(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE QuatData_proto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void QuatData_proto::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, qx_),
           0,
           offsetof(Impl_, qw_) -
               offsetof(Impl_, qx_) +
               sizeof(Impl_::qw_));
}
QuatData_proto::~QuatData_proto() {
  // @@protoc_insertion_point(destructor:QuatData_proto)
  _internal_metadata_.Delete<std::string>();
  SharedDtor();
}
inline void QuatData_proto::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
QuatData_proto::GetClassData() const {
  PROTOBUF_CONSTINIT static const ClassDataLite<15> _data_ =
      {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(QuatData_proto, _impl_._cached_size_),
              true,
          },
          "QuatData_proto",
      };

  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 0, 2> QuatData_proto::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(QuatData_proto, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_QuatData_proto_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::QuatData_proto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional float qw = 4;
    {::_pbi::TcParser::FastF32S1,
     {37, 3, 0, PROTOBUF_FIELD_OFFSET(QuatData_proto, _impl_.qw_)}},
    // optional float qx = 1;
    {::_pbi::TcParser::FastF32S1,
     {13, 0, 0, PROTOBUF_FIELD_OFFSET(QuatData_proto, _impl_.qx_)}},
    // optional float qy = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 1, 0, PROTOBUF_FIELD_OFFSET(QuatData_proto, _impl_.qy_)}},
    // optional float qz = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 2, 0, PROTOBUF_FIELD_OFFSET(QuatData_proto, _impl_.qz_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional float qx = 1;
    {PROTOBUF_FIELD_OFFSET(QuatData_proto, _impl_.qx_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional float qy = 2;
    {PROTOBUF_FIELD_OFFSET(QuatData_proto, _impl_.qy_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional float qz = 3;
    {PROTOBUF_FIELD_OFFSET(QuatData_proto, _impl_.qz_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional float qw = 4;
    {PROTOBUF_FIELD_OFFSET(QuatData_proto, _impl_.qw_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void QuatData_proto::Clear() {
// @@protoc_insertion_point(message_clear_start:QuatData_proto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    ::memset(&_impl_.qx_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.qw_) -
        reinterpret_cast<char*>(&_impl_.qx_)) + sizeof(_impl_.qw_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<std::string>();
}

::uint8_t* QuatData_proto::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:QuatData_proto)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional float qx = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        1, this->_internal_qx(), target);
  }

  // optional float qy = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        2, this->_internal_qy(), target);
  }

  // optional float qz = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        3, this->_internal_qz(), target);
  }

  // optional float qw = 4;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        4, this->_internal_qw(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:QuatData_proto)
  return target;
}

::size_t QuatData_proto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:QuatData_proto)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    // optional float qx = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 5;
    }

    // optional float qy = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 5;
    }

    // optional float qz = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += 5;
    }

    // optional float qw = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size += 5;
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  _impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void QuatData_proto::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const QuatData_proto*>(
      &from));
}

void QuatData_proto::MergeFrom(const QuatData_proto& from) {
  QuatData_proto* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:QuatData_proto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.qx_ = from._impl_.qx_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.qy_ = from._impl_.qy_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.qz_ = from._impl_.qz_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.qw_ = from._impl_.qw_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void QuatData_proto::CopyFrom(const QuatData_proto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:QuatData_proto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void QuatData_proto::InternalSwap(QuatData_proto* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(QuatData_proto, _impl_.qw_)
      + sizeof(QuatData_proto::_impl_.qw_)
      - PROTOBUF_FIELD_OFFSET(QuatData_proto, _impl_.qx_)>(
          reinterpret_cast<char*>(&_impl_.qx_),
          reinterpret_cast<char*>(&other->_impl_.qx_));
}

// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
