// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: SkelEntry.proto
// Protobuf C++ Version: 5.27.2

#ifndef GOOGLE_PROTOBUF_INCLUDED_SkelEntry_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_SkelEntry_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_SkelEntry_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_SkelEntry_2eproto {
  static const ::uint32_t offsets[];
};
class SkelEntry_proto;
struct SkelEntry_protoDefaultTypeInternal;
extern SkelEntry_protoDefaultTypeInternal _SkelEntry_proto_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class SkelEntry_proto final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:SkelEntry_proto) */ {
 public:
  inline SkelEntry_proto() : SkelEntry_proto(nullptr) {}
  ~SkelEntry_proto() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SkelEntry_proto(
      ::google::protobuf::internal::ConstantInitialized);

  inline SkelEntry_proto(const SkelEntry_proto& from) : SkelEntry_proto(nullptr, from) {}
  inline SkelEntry_proto(SkelEntry_proto&& from) noexcept
      : SkelEntry_proto(nullptr, std::move(from)) {}
  inline SkelEntry_proto& operator=(const SkelEntry_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline SkelEntry_proto& operator=(SkelEntry_proto&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const SkelEntry_proto& default_instance() {
    return *internal_default_instance();
  }
  static inline const SkelEntry_proto* internal_default_instance() {
    return reinterpret_cast<const SkelEntry_proto*>(
        &_SkelEntry_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(SkelEntry_proto& a, SkelEntry_proto& b) { a.Swap(&b); }
  inline void Swap(SkelEntry_proto* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SkelEntry_proto* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SkelEntry_proto* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::MessageLite::DefaultConstruct<SkelEntry_proto>(arena);
  }
  void CheckTypeAndMergeFrom(
      const ::google::protobuf::MessageLite& from) final;
  void CopyFrom(const SkelEntry_proto& from);
  void MergeFrom(const SkelEntry_proto& from);
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(SkelEntry_proto* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "SkelEntry_proto"; }

 protected:
  explicit SkelEntry_proto(::google::protobuf::Arena* arena);
  SkelEntry_proto(::google::protobuf::Arena* arena, const SkelEntry_proto& from);
  SkelEntry_proto(::google::protobuf::Arena* arena, SkelEntry_proto&& from) noexcept
      : SkelEntry_proto(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData() const final;

 public:
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPNodeNameFieldNumber = 3,
    kNodeIndexFieldNumber = 1,
    kParentIndexFieldNumber = 2,
  };
  // optional bytes pNodeName = 3;
  bool has_pnodename() const;
  void clear_pnodename() ;
  const std::string& pnodename() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_pnodename(Arg_&& arg, Args_... args);
  std::string* mutable_pnodename();
  PROTOBUF_NODISCARD std::string* release_pnodename();
  void set_allocated_pnodename(std::string* value);

  private:
  const std::string& _internal_pnodename() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pnodename(
      const std::string& value);
  std::string* _internal_mutable_pnodename();

  public:
  // optional sint32 nodeIndex = 1;
  bool has_nodeindex() const;
  void clear_nodeindex() ;
  ::int32_t nodeindex() const;
  void set_nodeindex(::int32_t value);

  private:
  ::int32_t _internal_nodeindex() const;
  void _internal_set_nodeindex(::int32_t value);

  public:
  // optional sint32 parentIndex = 2;
  bool has_parentindex() const;
  void clear_parentindex() ;
  ::int32_t parentindex() const;
  void set_parentindex(::int32_t value);

  private:
  ::int32_t _internal_parentindex() const;
  void _internal_set_parentindex(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:SkelEntry_proto)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_SkelEntry_proto_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SkelEntry_proto& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr pnodename_;
    ::int32_t nodeindex_;
    ::int32_t parentindex_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_SkelEntry_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SkelEntry_proto

// optional sint32 nodeIndex = 1;
inline bool SkelEntry_proto::has_nodeindex() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void SkelEntry_proto::clear_nodeindex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nodeindex_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int32_t SkelEntry_proto::nodeindex() const {
  // @@protoc_insertion_point(field_get:SkelEntry_proto.nodeIndex)
  return _internal_nodeindex();
}
inline void SkelEntry_proto::set_nodeindex(::int32_t value) {
  _internal_set_nodeindex(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:SkelEntry_proto.nodeIndex)
}
inline ::int32_t SkelEntry_proto::_internal_nodeindex() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.nodeindex_;
}
inline void SkelEntry_proto::_internal_set_nodeindex(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nodeindex_ = value;
}

// optional sint32 parentIndex = 2;
inline bool SkelEntry_proto::has_parentindex() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void SkelEntry_proto::clear_parentindex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.parentindex_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int32_t SkelEntry_proto::parentindex() const {
  // @@protoc_insertion_point(field_get:SkelEntry_proto.parentIndex)
  return _internal_parentindex();
}
inline void SkelEntry_proto::set_parentindex(::int32_t value) {
  _internal_set_parentindex(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:SkelEntry_proto.parentIndex)
}
inline ::int32_t SkelEntry_proto::_internal_parentindex() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.parentindex_;
}
inline void SkelEntry_proto::_internal_set_parentindex(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.parentindex_ = value;
}

// optional bytes pNodeName = 3;
inline bool SkelEntry_proto::has_pnodename() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void SkelEntry_proto::clear_pnodename() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pnodename_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& SkelEntry_proto::pnodename() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:SkelEntry_proto.pNodeName)
  return _internal_pnodename();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SkelEntry_proto::set_pnodename(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.pnodename_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:SkelEntry_proto.pNodeName)
}
inline std::string* SkelEntry_proto::mutable_pnodename() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_pnodename();
  // @@protoc_insertion_point(field_mutable:SkelEntry_proto.pNodeName)
  return _s;
}
inline const std::string& SkelEntry_proto::_internal_pnodename() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pnodename_.Get();
}
inline void SkelEntry_proto::_internal_set_pnodename(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.pnodename_.Set(value, GetArena());
}
inline std::string* SkelEntry_proto::_internal_mutable_pnodename() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.pnodename_.Mutable( GetArena());
}
inline std::string* SkelEntry_proto::release_pnodename() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:SkelEntry_proto.pNodeName)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.pnodename_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.pnodename_.Set("", GetArena());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void SkelEntry_proto::set_allocated_pnodename(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.pnodename_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.pnodename_.IsDefault()) {
          _impl_.pnodename_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SkelEntry_proto.pNodeName)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_SkelEntry_2eproto_2epb_2eh
